# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f594170e49e2a1ca224b8ecac2ebf71fcee9bb3a1bba21ee36328f43ca8fb3245326ee0d018491572d3b53682c9dc048b93cf68cdb8d4d5ee11b0d8334b1ab86

test:
  secret_key_base: 295498713ff3bdc10964894ff1f71be00f9e6a73a9ab16c3b7f496c0c86d9a993b3a58bff0b0f5a03cf2d1f48f94b29f2d913b64555c07df29833ba576e3c97c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
